version: '3.8'
services:
  app:
    build:
      context: ./app
    environment:
      VERSION: initial

  nginx:
    build:
      context: ./nginx
    environment:
      APP_HOST: app
    ports:
      - "80:80"
    depends_on:
      - app
